apiVersion: v1
kind: Service
metadata:
  name: "lb-prod-apache"
  namespace: "prod"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    external-dns.alpha.kubernetes.io/hostname: prod.k8s-example.cloud.library.jhu.edu

spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "apache"
