apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 

bases:
  - ../../../base/
  - ./mysql_backup/
  - ./volumes/
  
resources:
  - mysqlsealed.yaml
  - namespace.yaml

patches:
  - path: turkle_service_metadata.yaml
    
namespace: demo
