apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 

bases:
  - ../../../base/
  - ./mysql_backup/
  - ./volumes/

resources:
  - namespace.yaml
  - loadbalancer.yaml

  patches:
  - path: turkle_service_annotations.yaml
    
namespace: dev
