apiVersion: v1
kind: Service
metadata:
  name: turkle-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    external-dns.alpha.kubernetes.io/hostname: k8s-turkle.cloud.library.jhu.edu
spec:
  type: NodePort
  selector:
    app: turkle
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: "turkle"
