apiVersion: v1
kind: Service
metadata:
  name: "lb-dev-apache"
  namespace: "dev"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dev.k8s-example-azure.cloud.library.jhu.edu
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "apache"
