name: Trigger remote dispatch
on:
  push:
    branches: [ master ]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: use ghscript
        uses: actions/github-script@v3.0.0
        with:
          github_token: ${{ secret.AUTOOPS_PAT }}
          script: |
            return github.actions
               .listRepoWorkflows({
                    owner: "jhu-library-operations",
                    repo: "turkle-k8s-project"
            })
