name: Trigger remote dispatch
on:
  push:
    branches: [ master ]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: use ghscript
        uses: actions/github-script@v3.0.0
        with:
          github-token: ${{ secrets.AUTOOPS_PAT }}
          script: |
            return github.actions
               .listRepoWorkflows({
                    owner: "jhu-library-operations",
                    repo: "turkle-k8s-project"
            }).then(workflows_result => {
              let workflows = workflows.data.workflows
                 .filter(a => a.name === "Submodule Dispatch" && a.state === "active")
                 .map(a => a.id);
              if (workflows.length === 0){
                throw "no workflows"
              }

              return workflows[0]
            }).then(workflow_id => {
              console.log(workflow_id)
            })
